// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8755)
// Generated by LuaStick, Jun  3 2021.

#pragma once

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8763)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8763)
#include "main.h"

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8773)
struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
