// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8025)
// Generated by LuaStick, Jun  6 2020.

#pragma once

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8033)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8033)
#include "main.h"

struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
