// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8618)
// Generated by LuaStick, May 27 2021.

#pragma once

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8626)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8626)
#include "main.h"

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8636)
struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
