// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8807)
// Generated by LuaStick, Jun 11 2021.

#pragma once

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8815)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8815)
#include "main.h"

// Generated at "c:\src\lua\luastick\luastick\src\luastick.cpp"(8825)
struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
